config/routes.rb
Soundproject::Application.routes.draw do   
    
  devise_for :users do     
    
    resources :events
  end
  resources :friendships

  match "home" => "welcome#index"
  match "sources" => "events#sources"
  
  root :to => "events#index"

end

app/models/event.rb
class Event < ActiveRecord::Base
  attr_accessible :user_id, :time_and_duration, :artist_name, :price, :description, :date, :track_url, :picture
  has_attached_file :picture, :styles => { :normal => "500x320>" },
                  :url  => "/assets/events/:id/:style/:basename.:extension",
                  :path => ":rails_root/public/assets/events/:id/:style/:basename.:extension"
  has_attached_file :picture_thumbnail, :styles => { :small => "260x260>" },
                  :url  => "/assets/events/:id/:style/:basename.:extension",
                  :path => ":rails_root/public/assets/events/:id/:style/:basename.:extension"                
  belongs_to :user
  validates_presence_of :time_and_duration, :artist_name, :price, :description, :date
  validates_attachment_size :picture, :less_than => 3.megabytes
  validates_attachment_content_type :picture, :content_type => ['image/jpeg', 'image/png']
end

app/models/friendship.rb
class Friendship < ActiveRecord::Base
  attr_accessible :friend_id, :user_id
  belongs_to :user
  belongs_to :friend, :class_name => "User"
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :full_name,:email, :password, :password_confirmation, :remember_me
  # attr_accessible :title, :body
  has_many :events
  has_many :friendships
  has_many :friends, :through => :friendships
  has_many :inverse_friendships, :class_name => "Friendship", :foreign_key => "friend_id"
  has_many :inverse_friends, :through => :inverse_friendships, :source => :user
  def has_follow? friend
     friendships.find_by_friend_id friend.id
  end
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
	before_filter :authenticate_user!, :only => [:new, :create]
	def index
		@events = Event.all
        @events = Event.order(:date).page(params[:page]).per(6)
	end
	def new
    @event = Event.new

    	respond_to do |format|
      		format.html # new.html.erb
      		format.json { render json: @event }
    	end
  	end
		def create
		@event = Event.new(params[:event])		
		
		    respond_to do |format|
		      if @event.save
		      	@event.picture_thumbnail = @event.picture
		      	@event.save
		        format.html { redirect_to @event, notice: 'Event was successfully created. I cant wait!' }
                #UserMailer.event_registration(@event.user).deliver
		        format.json { render json: @post, event: :created, location: @post }
		      else
		        format.html { render action: "new" }
		        format.json { render json: @event.errors, post: :unprocessable_entity }
		      end
		    end
		end

	def show
	    @event = Event.find(params[:id])

    	respond_to do |format|
      	format.html # show.html.erb
      	format.json { render json: @event }
    	end
	end
	def sources
        @events= []
        current_user.friendships.each do |friendship|
        @events+=Event.where(:user_id => friendship.friend_id)
        end
    end
    	
end

app/controllers/friendships_controller.rb
class FriendshipsController < ApplicationController
def create
  @friendship = current_user.friendships.build(:friend_id => params[:friend_id])
  if @friendship.save
    flash[:notice] = "Followed."
    
    respond_to do |format|
      format.html { redirect_to root_url }# index.html.erb
      format.js {render :replace}
      end
  else
    flash[:error] = "Unable to follow."
    respond_to do |format|
      # index.html.erb
      format.js {render :replace}
      end
  end
end

def destroy
  @friendship = current_user.friendships.find(params[:id])
  @friendship.destroy
  flash[:notice] = "Unfollowed"
  redirect_to root_url
end
end

app/controllers/users_controller.rb
class UsersController < Devise::SessionsController
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/events/_form.html.erb
<%= simple_form_for(@event) do |f| %>
  <% if @event.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@event.errors.count, "error") %> prohibited this event from being saved:</h2>

      <ul>
      <% @event.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="span4">
    <div class="well">
    <%=f.hidden_field :user_id, :value => current_user.id %>
    <%=f.input :date, :input_html => { :size => 20, :id => "datepicker" } %>
    <%=f.input :time_and_duration, :title => "At what time and how long it's gonna be" %>    
    <%=f.input :price%>
    <%=f.input :description , :input_html => {:rows => 4}%>
    <%=f.file_field :picture, :id => "file"%>
    <p>Choose a picture</p>
    <div class="controls">
      <div class="dummyfile">
      <input id="filename" type="text" class="input disabled" name="filename" readonly>
      <a id="fileselectbutton" class="btn btn-warning btn-small">Choose</a>
      </div>
    <%= f.input :artist_name, as: :string %>    
    <%= f.input :track_url, collection: [@event.track_url], :prompt => "Select the track"%>
    <%= f.button :submit , :class => "btn btn-inverse" %>
    </div>
  </div>  

<% end %>
</div>

app/views/events/index.html.erb
<script type="text/javascript" src="http://localhost:3000/widget/ilove"></script>
<iframe src="http://localhost:3000/lists/1"></iframe>
<h1>Concerts</h1>

<%=paginate @events%>	
	<% @events.each do |event| %>
		<div class="row">
		<%user=User.find(event.user_id)%>
		<blockquote>
			<% if event.picture.url(:normal)!="/pictures/normal/missing.png"%>
			<div id="pic_small" class="img-po<%paginate @events%>laroid pull-right"><%= image_tag event.picture.url(:small) %></div><%end%>
			<h2><%= event.artist_name.capitalize%> Concert</h2>
			<p>It will be on: <%= event.date %></p>
			<p>It will be at and last: <%= event.time_and_duration %></p>
			<p>The ticket will cost you: $<%= event.price %> bucks</p>
			<small>Submitted by: <%=user.full_name%>
			</small>
			<%= link_to "Check it out!",event, :class => "btn btn-warning"%>

		</blockquote>
	</div>
	<%end%>

app/views/events/new.html.erb
<script>
    $(function() {
        $( "#datepicker" ).datepicker({
            numberOfMonths: 3,
            showButtonPanel: true
        });
    });
    </script>
<h1>New Event</h1>
<div class="row">
    
	<div class="span4">
	<%= render 'form' %>
	</div>
	<div class="span6" id="concierto">         
            <% image_tag("concert.jpg") %>
  			<img src="/assets/concert.jpg" alt="Icon" />           
    </div> 
</div>

<%= link_to 'Back', events_path %>

app/views/events/show.html.erb
<div class="row">
<% if @event.picture.url(:normal)!="/pictures/normal/missing.png"%>
<div id="show_pic" class="pull-left"><%= image_tag @event.picture.url(:normal) %></div>
<%end%>
<div id="info">
<%user=User.find(@event.user_id)%>
<h1><%= @event.artist_name.capitalize %> Concert</h1>

<p>It will be on: <%= @event.date %></p>
<p>It will be at and last: <%= @event.time_and_duration %></p>
<p>The ticket will cost you: $<%= @event.price %> bucks</p>
<p>More info: <%= @event.description %></p>
<small>Submitted by: <%=user.full_name%><% if user_signed_in? && user!=current_user %>
	<%= render :partial => "friendships/follow_button", :locals => {:user => user} %>
					 <%end%>
</div>
</div>
	<%if @event.track_url!="no provided" && @event.track_url!=""%>
		<blockquote>
		<h2>Sample Track</h2>
		<p >
		    <% # create a client object with your app credentials
		        client = Soundcloud.new(:client_id => '5e75f69e6e9591de61fc8a7a5dd6de11')
		        track_url = @event.track_url
		        embed_info = client.get('/oembed', :url => track_url)%>
		        <%=embed_info['html'].html_safe%>                    
		    </p>
		</blockquote>
	<%end%>

app/views/events/sources.html.erb
<h1>Concerts</h1>
<% for user in current_user.friends %>
  <% user.events.each do |event| %>
  		<div class="row">
		<%user=User.find(event.user_id)%>
		<blockquote>
			<% if event.picture.url(:normal)!="/pictures/normal/missing.png"%>
			<div id="pic_small" class="img-polaroid pull-right"><%= image_tag event.picture.url(:small) %></div><%end%>
			<h2><%= event.artist_name.capitalize%> Concert</h2>
			<p>It will be on: <%= event.date %></p>
			<p>It will be at and last: <%= event.time_and_duration %></p>
			<p>The ticket will cost you: $<%= event.price %> bucks</p>
			<small>Submitted by: <%=user.full_name%>
			</small>
			<%= link_to "Check it out!",event, :class => "btn btn-warning"%>

		</blockquote>
	</div>
	<%end%>
  <% end %>

	

app/views/friendships/_follow_button.html.erb
<div id="follow%>">
<% if current_user.has_follow?(user)%>
	<%= button_to "Unfollow", friendship_path(current_user.friendships.where(:friend_id => user.id).first), :data => { :confirm => "Do you really want to unfollow this guy?" }, :method => :delete, class: "btn btn-warning btn-small" %>
<%else%>
	<%= button_to "Follow", friendships_path(:friend_id => user), :method => :post, class: "btn btn-success btn-small"  %>
<%end%>
<% i=0
	for user in user.inverse_friends %>
				
	<% i=i+1 %>	
	<% end %><%= i %> followers
</small>
</div>

app/views/friendships/replace.js.erb
$('#follow').replaceWith('<%= j render(:partial => "friendships/follow_button"%>');

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Welcome to SoundProject</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
   
  <meta charset="utf-8" />
    <title>jQuery UI Accordion - Default functionality</title>
    <link rel="stylesheet" href="http://code.jquery.com/ui/1.9.1/themes/base/jquery-ui.css" />
    <script src="http://code.jquery.com/jquery-1.8.2.js"></script>
    <script src="http://code.jquery.com/ui/1.9.1/jquery-ui.js"></script>
    <link rel="stylesheet" href="/resources/demos/style.css" />
    <script src="http://connect.soundcloud.com/sdk.js"></script>
  	<script type="text/javascript">
		  SC.initialize({
		    client_id: '5e75f69e6e9591de61fc8a7a5dd6de11'
		  });
  	</script>
    <script>
   
    $(function() {
        $( "#accordion" ).accordion();
    });
    </script>
</head>
<body>

<div class = "navbar navbar-fixed-top" >
	<div class = "navbar-inner">
		<div class="container">
			<a class = "brand" href="#" >SoundProject</a>
			<ul class="nav">				
				<li><%= link_to "Events", root_path %></li>
				<li><%= link_to "Home", home_path%></li>
				<% if user_signed_in? %>
				<li><%= link_to "My Sources", sources_path%></li>
				<%end%>
			</ul>
			<ul class="nav pull-right">
				<% if user_signed_in? %>
				<li><%= link_to "Create an Event", new_event_path %></li>
				<li><%= link_to current_user.full_name, edit_user_registration_path %></li>
				<li><%= link_to "Log out", destroy_user_session_path, method: :delete %></li>
				<% else %>
				<li><%= link_to "Log in", user_session_path%></li>
				
				<li><%= link_to "Register", new_user_registration_path%></li>						
				<% end %>
			</ul>
		</div>		
	</div>
	</div>
	
	<div class="container">					
		<% if flash[:notice] %>
			<div class="alert alert-success">
				<button type="button" class="close" data-dismiss="alert">x</button>
  				<%= flash[:notice] %>
			</div>
		<% end %>
		<% if flash[:alert] %>
			<div class="alert alert-error">
				<button type="button" class="close" data-dismiss="alert">×</button>
  				<%= flash[:alert] %>
			</div>
		<% end %>
			<%= yield %>
	</div>

</body>
</html>

app/views/welcome/index.html.erb
<h1>Welcome to SoundProject</h1>
    
    <div class="row">
        <div class="span6">         
            <img src="assets/index.png" class="img-rounded">            
        </div>  
        <div class="span4">
            <div class="well">
                <h2>Sign Up Today!</h2>
                <h3>It's very easy</h3>
                <p>Phasellus sit amet diam metus, sed feugiat enim. Aenean sit amet facilisis erat. Nam ac orci augue. Phasellus pellentesque, purus ut pellentesque blandit, ipsum ipsum lacinia eros, in venenatis tortor tellus ut elit. Sed sed nisi sit amet turpis scelerisque scelerisque ut nec velit. In hac habitasse platea dictumst. </p> 

                <%= link_to  "Sign Up",new_user_registration_path, :class => "btn btn-warning btn-large"%>                           
            </div>  
                  
        </div>  
    </div>  
    <div class="well">
            <% # register a client with YOUR_CLIENT_ID as client_id_
                    client = Soundcloud.new(:client_id => '5e75f69e6e9591de61fc8a7a5dd6de11')
                    # get 10 hottest tracks
                    tracks = client.get('/tracks', :limit => 5, :order => 'hotness')                    
                    %>             
    <h2>Top 5 Hottest Song Of The Week</h2>               
    <div id="accordion">
        <% tracks.each do |track| %>
            <h3><%=track.title%></h3>
            <div>
                <p>
                <% # create a client object with your app credentials
                    client = Soundcloud.new(:client_id => '5e75f69e6e9591de61fc8a7a5dd6de11')

                    # get a tracks oembed data
                    track_url = track.permalink_url
                    embed_info = client.get('/oembed', :url => track_url)

                    # print the html for the player widget
                    %>
                    <%=embed_info['html'].html_safe%>                    
                </p>
            </div>
        <%end%>    
</div>
           